controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    forward_position_controller:
      type: position_controllers/ForwardCommandController
      publish_rate: 50

forward_position_controller:
  ros__parameters:
    joints:
      - first_joint
    interface_name: position